pipeline {
    agent { label 'linux-node1' }

    environment {
        JAVA_HOME = '/usr/lib/jvm/java-21-openjdk-amd64'
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Build') {
            steps {
                sh '''
                java -version
                mvn -B -DskipTests clean package
                '''
            }
        }
    }
}
